// ============================================================
// Centralized configuration constants
// ============================================================

// --- MediaPipe Landmarks ---
export const LANDMARK = {
  WRIST: 0,
  THUMB_CMC: 1, THUMB_MCP: 2, THUMB_IP: 3, THUMB_TIP: 4,
  INDEX_MCP: 5, INDEX_PIP: 6, INDEX_DIP: 7, INDEX_TIP: 8,
  MIDDLE_MCP: 9, MIDDLE_PIP: 10, MIDDLE_DIP: 11, MIDDLE_TIP: 12,
  RING_MCP: 13, RING_PIP: 14, RING_DIP: 15, RING_TIP: 16,
  PINKY_MCP: 17, PINKY_PIP: 18, PINKY_DIP: 19, PINKY_TIP: 20,
} as const;

export const FINGERTIP_INDICES = [LANDMARK.THUMB_TIP, LANDMARK.INDEX_TIP, LANDMARK.MIDDLE_TIP, LANDMARK.RING_TIP, LANDMARK.PINKY_TIP] as const;
export const PALM_INDICES = [LANDMARK.WRIST, LANDMARK.INDEX_MCP, LANDMARK.MIDDLE_MCP, LANDMARK.RING_MCP, LANDMARK.PINKY_MCP] as const;

export const FINGER_CHAINS = [
  [LANDMARK.THUMB_CMC, LANDMARK.THUMB_MCP, LANDMARK.THUMB_IP, LANDMARK.THUMB_TIP],
  [LANDMARK.INDEX_MCP, LANDMARK.INDEX_PIP, LANDMARK.INDEX_DIP, LANDMARK.INDEX_TIP],
  [LANDMARK.MIDDLE_MCP, LANDMARK.MIDDLE_PIP, LANDMARK.MIDDLE_DIP, LANDMARK.MIDDLE_TIP],
  [LANDMARK.RING_MCP, LANDMARK.RING_PIP, LANDMARK.RING_DIP, LANDMARK.RING_TIP],
  [LANDMARK.PINKY_MCP, LANDMARK.PINKY_PIP, LANDMARK.PINKY_DIP, LANDMARK.PINKY_TIP],
] as const;

// --- Gesture Detection ---
export const GESTURE = {
  PINCH_ENTER_THRESHOLD: 0.05,
  PINCH_EXIT_THRESHOLD: 0.07,
  SPREAD_THRESHOLD: 0.3,
  LERP_FACTOR: 0.3,
} as const;

// --- Grip Detection ---
export const GRIP = {
  HYSTERESIS_FRAMES: 3,
  FIST_THRESHOLD: 0.7,
  OPEN_THRESHOLD: 0.3,
  PINCH_OPEN_THRESHOLD: 0.3,
  PINCH_CURL_THRESHOLD: 0.5,
  PINCH_TIP_DISTANCE: 0.05,
  POINT_OPEN_THRESHOLD: 0.3,
  POINT_CURL_THRESHOLD: 0.6,
  NON_THUMB_FINGER_COUNT: 4,
} as const;

// --- Hand Physics ---
export const PHYSICS = {
  EMA_ALPHA: 0.4,
  DOMINANT_AXIS_THRESHOLD: 0.01,
} as const;

// --- Motion Recognition ---
export const MOTION = {
  BUFFER_CAPACITY: 30,
  SWIPE_SPEED_THRESHOLD: 0.8,
  SWIPE_MIN_FRAMES: 5,
  STATIC_SPEED_LIMIT: 0.02,
  STATIC_MIN_FRAMES: 15,
  ACCEL_BURST_SPEED_NOW: 0.5,
  ACCEL_BURST_SPEED_PREV: 0.1,
  ACCEL_BURST_LOOKBACK: 3,
  CIRCULAR_MIN_ANGLE_CHANGE: 0.01,
  CIRCULAR_MAX_REVERSAL_RATIO: 0.2,
  TARGET_FPS: 30,
} as const;

// --- Interaction Controller ---
export const INTERACTION = {
  EDGE_THRESHOLD: 0.08,
  EDGE_LANDMARK_INDICES: [0, 8] as readonly number[],
  SHAKE_CLEAR_VELOCITY: 0.3,
  SHAKE_CLEAR_REVERSALS: 4,
  SHAKE_CLEAR_DEBOUNCE_MS: 2000,
  SHAKE_CLEAR_INTERVAL_MS: 150,
  SHAKE_HISTORY_SIZE: 15,
  PARTIAL_GRAB_ENTER: 0.65,
  PARTIAL_GRAB_EXIT: 0.8,
  SWIPE_DEBOUNCE_MS: 1000,
} as const;

// --- Object Management ---
export const OBJECTS = {
  SIZE: 80,
  MAX_COUNT: 20,
  ADD_DEBOUNCE_MS: 500,
  COLLISION_FIND_ATTEMPTS: 50,
} as const;

// --- Collision ---
export const COLLISION = {
  ITERATIONS: 3,
  PANEL_GAP: 4,
} as const;

// --- Camera ---
export const CAMERA = {
  WIDTH: 640,
  HEIGHT: 480,
  NUM_HANDS: 2,
  MIN_DETECTION_CONFIDENCE: 0.7,
  MIN_PRESENCE_CONFIDENCE: 0.7,
  MIN_TRACKING_CONFIDENCE: 0.5,
} as const;

// --- Telemetry Logger ---
export const TELEMETRY_LOGGER = {
  VELOCITY_SPIKE_THRESHOLD: 0.4,
  SHAKE_REVERSAL_THRESHOLD: 4,
  ACCELERATION_THRESHOLD: 0.3,
  SUDDEN_STOP_THRESHOLD: 0.05,
  SNAPSHOT_INTERVAL_MS: 1000,
  EVENT_DEBOUNCE_MS: 300,
  HISTORY_SIZE: 15,
  MAX_LOG_ENTRIES: 500,
  CLAP_MIN_VELOCITY: 0.4,
  CLAP_DEBOUNCE_MS: 1500,
  CLAP_SLOW_THRESHOLD: 0.15,
  CLAP_CLOSE_THRESHOLD: 0.15,
  CLAP_TIMEOUT_MS: 500,
  CLAP_OCCLUSION_MS: 400,
  SHAKE_ANGLE_THRESHOLD: 0.3,
  SHAKE_SPEED_THRESHOLD: 0.15,
  MOVING_SPEED_THRESHOLD: 0.1,
} as const;

// --- Telemetry Recorder ---
export const TELEMETRY_RECORDER = {
  DEFAULT_CAPACITY: 90,
  MAX_GESTURE_EVENTS: 1000,
} as const;

// --- Batch Telemetry ---
// (These are hook params, not extracted — they have defaults in the hook)

// --- UI / Hand Analysis ---
export const UI = {
  THROTTLE_MS: 100,
  OBJECT_BORDER_RADIUS: 8,
  TRANSITION_DURATION_MS: 150,
} as const;

// --- Panel Dimensions ---
export const PANEL = {
  CAMERA_WIDTH: 320,
  CAMERA_HEIGHT: 240,
  TITLE_BAR_HEIGHT: 28,
  HIT_BUFFER: 10,
  HUD_WIDTH: 200,
  HUD_MAX_HEIGHT: 600,
  EVENT_LOG_WIDTH: 320,
  EVENT_LOG_MAX_HEIGHT: 300,
  EVENT_LOG_VISIBLE_ENTRIES: 50,
} as const;

// --- Object Tracker ---
export const TRACKER = {
  MOVING_SPEED_THRESHOLD: 1,
} as const;

// --- Telemetry Visualization ---
export const TELEMETRY_VIS = {
  TIMELINE_WINDOW_MS: 5000,
  TIMELINE_CANVAS_HEIGHT: 56,
  GESTURE_BAR_Y: 8,
  GESTURE_BAR_HEIGHT: 20,
  VELOCITY_TICK_Y: 32,
  VELOCITY_TICK_HEIGHT: 20,
  VELOCITY_SPIKE_THRESHOLD: 15,
  SKELETON_LINE_WIDTH: 1.5,
  SKELETON_LANDMARK_RADIUS: 3,
  ARROW_MAX_LENGTH: 60,
  ARROWHEAD_BASE: 8,
  ARROWHEAD_DEPTH: 12,
  ARROW_LINE_WIDTH: 1.5,
  ARROW_SPEED_THRESHOLD: 1,
  ARROW_LENGTH_MULTIPLIER: 4,
  GRIP_INDICATOR_RADIUS: 22,
  GRIP_INDICATOR_STROKE: 3,
  HUD_SPEED_THRESHOLDS: [50, 200, 500] as readonly number[],
  HUD_PIXEL_MULTIPLIER: 1200,
  HUD_CURL_BAR_HEIGHT: 20,
  HUD_CURL_RED_THRESHOLD: 0.7,
  HUD_CURL_YELLOW_THRESHOLD: 0.3,
  HUD_GRIP_FORCE_MULTIPLIER: 100,
  FPS_GREEN_THRESHOLD: 50,
  FPS_YELLOW_THRESHOLD: 30,
} as const;

// --- Color Thresholds ---
export const COLOR_THRESHOLDS = {
  SPEED_LOW: 2,
  SPEED_MED: 8,
  SPEED_HIGH: 20,
  GRIP_LOW: 0.3,
  GRIP_HIGH: 0.7,
} as const;

// --- Spatial Tracking ---
export const SPATIAL = {
  SCORE_SEMANTIC_INTERACTIVE: 3,
  SCORE_HAS_LISTENERS: 2,
  SCORE_MIN_DIMENSIONS: 1,
  SCORE_GENERIC_CONTAINER: -2,
  SCORE_DATA_TRACKABLE: 5,
  MIN_ELEMENT_WIDTH: 20,
  MIN_ELEMENT_HEIGHT: 20,
  EVICTION_FRAMES: 30,
  SNAP_THRESHOLD: 15,
  PROXIMITY_THRESHOLD: 50,
  HOVER_EVENT_INTERVAL_MS: 500,
  RECT_UPDATE_INTERVAL_MS: 100,
  INTERACTIVE_SCORE_THRESHOLD: 2,
  // UI Feedback
  HIGHLIGHT_OUTLINE_WIDTH: 2,
  HIGHLIGHT_OUTLINE_OFFSET: 3,
  HIGHLIGHT_COLOR_RIGHT: '#4ECDC4',
  HIGHLIGHT_COLOR_LEFT: '#FF6B6B',
  PROXIMITY_GLOW_MAX_BLUR: 15,
  PROXIMITY_GUIDE_OPACITY: 0.2,
  PROXIMITY_LABEL_SIZE: 10,
  MAX_PROXIMITY_TARGETS: 3,
  HUD_EVENT_FEED_MAX: 20,
  HUD_THROTTLE_MS: 100,
} as const;
